"""create collection runs and query matches tables

Revision ID: 8c4f1b6e9d72
Revises: 7b3e0a5d8c61
Create Date: 2026-08-12

Two tables, both in service of one promise: collection starts on its own and counts each
post once (E03-S01).

`collection_runs` is the polling queue *and* the log of what polling did. A queue in the
database rather than in a process, because a title whose next poll was lost with a deploy
looks exactly like a title nobody is talking about. `(status, scheduled_for)` is indexed
first because a worker asks "what is due" far more often than it asks about any one title.

`mention_query_matches` is the half of the fan-out that deduplication would otherwise
destroy. A cycle runs several overlapping queries and the same popular post comes back on
more than one; the `mentions` unique constraint sees to it that this is one row, and this
table remembers which queries found it. `(mention_id, query_variant)` is unique because
polls overlap by design — without it, the attribution counts would measure how often a
title is polled rather than which of its terms are working.
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "8c4f1b6e9d72"
down_revision: str | None = "7b3e0a5d8c61"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "collection_runs",
        sa.Column("title_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "QUEUED",
                "RUNNING",
                "SUCCEEDED",
                "FAILED",
                "SKIPPED",
                name="collection_run_status",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "trigger",
            sa.Enum(
                "TITLE_CREATED",
                "SCHEDULED",
                "MANUAL",
                name="collection_run_trigger",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("scheduled_for", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("polls_per_day", sa.Integer(), nullable=False),
        sa.Column("variants_planned", sa.Integer(), nullable=False),
        sa.Column("pages_fetched", sa.Integer(), nullable=False),
        sa.Column("mentions_stored", sa.Integer(), nullable=False),
        sa.Column("mentions_already_known", sa.Integer(), nullable=False),
        sa.Column("unreadable", sa.Integer(), nullable=False),
        sa.Column("failure_reason", sa.String(length=500), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["title_id"], ["titles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_collection_run_status_scheduled_for",
        "collection_runs",
        ["status", "scheduled_for"],
        unique=False,
    )
    op.create_index(
        "ix_collection_run_title_scheduled_for",
        "collection_runs",
        ["title_id", "scheduled_for"],
        unique=False,
    )
    op.create_index(
        op.f("ix_collection_runs_title_id"), "collection_runs", ["title_id"], unique=False
    )
    # One pending cycle per title, enforced rather than checked. The service reads
    # "is anything pending?" before inserting, but a read followed by an insert is a race
    # two processes both win, and the cost of losing it is a title polled twice per cycle
    # with two workers colliding on the `mentions` unique constraint.
    #
    # Partial, because finished runs are the history and a title accumulates thousands of
    # them. Note the values: SQLAlchemy's `Enum` persists a Python enum's *name*, so the
    # stored text is "QUEUED"/"RUNNING", not "queued"/"running".
    op.create_index(
        "uq_collection_run_one_pending_per_title",
        "collection_runs",
        ["title_id"],
        unique=True,
        postgresql_where=sa.text("status IN ('QUEUED', 'RUNNING')"),
        sqlite_where=sa.text("status IN ('QUEUED', 'RUNNING')"),
    )
    op.create_table(
        "mention_query_matches",
        sa.Column("title_id", sa.Uuid(), nullable=False),
        sa.Column("mention_id", sa.Uuid(), nullable=False),
        sa.Column(
            "platform",
            sa.Enum("X", "INSTAGRAM", "REDDIT", "YOUTUBE", name="platform", native_enum=False),
            nullable=False,
        ),
        sa.Column("query_variant", sa.String(length=320), nullable=False),
        sa.Column("first_matched_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["mention_id"], ["mentions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["title_id"], ["titles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "mention_id", "query_variant", name="uq_mention_query_match_mention_variant"
        ),
    )
    op.create_index(
        "ix_mention_query_match_title_variant",
        "mention_query_matches",
        ["title_id", "query_variant"],
        unique=False,
    )
    op.create_index(
        op.f("ix_mention_query_matches_mention_id"),
        "mention_query_matches",
        ["mention_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_mention_query_matches_title_id"),
        "mention_query_matches",
        ["title_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_mention_query_matches_title_id"), table_name="mention_query_matches")
    op.drop_index(op.f("ix_mention_query_matches_mention_id"), table_name="mention_query_matches")
    op.drop_index("ix_mention_query_match_title_variant", table_name="mention_query_matches")
    op.drop_table("mention_query_matches")
    op.drop_index("uq_collection_run_one_pending_per_title", table_name="collection_runs")
    op.drop_index(op.f("ix_collection_runs_title_id"), table_name="collection_runs")
    op.drop_index("ix_collection_run_title_scheduled_for", table_name="collection_runs")
    op.drop_index("ix_collection_run_status_scheduled_for", table_name="collection_runs")
    op.drop_table("collection_runs")
    # ### end Alembic commands ###
